### ISSUE TITLE
Literal in Symbol Table ?

### ISSUE THREAD

**Issue by Yojda** [LimpSword/gada#1]
![image](https://github.com/LimpSword/gada/assets/88156239/c7129099-48ea-41e7-8418-e2f25bc911ff)

Chaque ligne, c'est un élément de la liste de tokens après lexer avec : token.Type token.Position token.Value
Est-ce qu'on met les littéraux en position autre que 0, cad dans la table des symboles

L'exemple est celui de inlineComment, le code : 
with Text_IO; --use Text_IO;
333 "let's"; -- random -- comment --doing--
      --begin
      45.26;
  hwy; ----------

**Comment by LimpSword** [comment]
Là, les littéraux ne sont jamais en position 0 ? Ils sont toujours ajoutés à une table non ?

**Comment by Yojda** [comment]
Oui, ils sont ajoutés à une table des symboles, mais pour moi ça devrait pas être le cas. Pour moi c'est uniquement les identifiants.
